### ISSUE TITLE
Add ability to enter custom public key and encryption algorithm for recipient manually

### ISSUE THREAD

**Issue by tboeckmann** [mailchain/mailchain-web#101]
**Is your feature request related to a problem? Please describe.**
When a message is sent to an address, the public key for the public address is used to encrypt the message and message location details.

**Describe the solution you&#x27;d like**
A user should be able to specify the public key and select from a list of supported algorithms use to encrypt the message.

**Additional context**
related to issue: #35 and #100

**Comment by robdefeo** [comment]
Closing due to archiving repository
