### ISSUE TITLE
NPM audit Report

### ISSUE THREAD

**Issue by developerfred** [mailchain/mailchain-web#103]
**Describe the bug**
  === npm audit security report ===                        
  https://gist.github.com/developerfred/59dc96740537986738f746efd48d76cd                                                                              

**To Reproduce**
1. npm install 

**Expected behavior**

**Screenshots**
<img width="580" alt="Screen Shot 2019-11-14 at 19 27 40" src="https://user-images.githubusercontent.com/57037080/68901559-e6bb5b00-0714-11ea-831a-44077839f8dd.png">

**Additional context**

**Comment by tboeckmann** [comment]
solved by #83
