### ISSUE TITLE
Remove unnecessary code in `inbox-compose.component.ts`

### ISSUE THREAD

**Issue by tboeckmann** [mailchain/mailchain-web#106]
**Describe the bug**
In `inbox-compose.component.ts`, the following line does nothing:

`this.modalConnectivityError.content.closeBtnName = 'Close'`

It should either serve a purpose or be removed.

**Additional context**
The modal handles the button text via the template (`modal-connectivity-error.component.html`).

**Comment by ayeniblessing101** [comment]
Hi @tboeckmann 

Please I will like to work on this issue

Regards
Blessing

**Comment by robdefeo** [comment]
Closing due to archiving repository
