### ISSUE TITLE
Add pagination / load more messages to inbox

### ISSUE THREAD

**Issue by tboeckmann** [mailchain/mailchain-web#109]
**Is your feature request related to a problem? Please describe.**
When I have hundreds of messages, it takes some time for the page to load. I don't always need to load last year's messages.

**Describe the solution you'd like**
Introduce pagination or a 'Load More Messages' button to add more messages to the view.

**Describe alternatives you've considered**
Infinite scroll that loads more messages automatically. This can be confusing for users though.

**Additional context**
Search functionality should also be compatible. (https://github.com/mailchain/mailchain/issues/277)

**Comment by robdefeo** [comment]
Closing due to archiving repository
