### ISSUE TITLE
Convert existing modal to 2 step wizard

### ISSUE THREAD

**Issue by tboeckmann** [mailchain/mailchain-web#157]
**Is your feature request related to a problem? Please describe.**
As a user, when I click 'Network' in the Mailchain inbox, a modal appears to change network.
![image](https://user-images.githubusercontent.com/2022378/74560822-671c7280-4f35-11ea-8994-03f0980fb2f0.png)

The modal needs to be adjusted according to the design to provide a wizard-like experience for selecting:
- [ ] the protocol
- [ ] the network

**Describe the solution you'd like**

The steps should look like this:

**Step 1**
![image](https://user-images.githubusercontent.com/2022378/74561095-f45fc700-4f35-11ea-97e1-101ec5b9a2b1.png)

**Step 2**
![image](https://user-images.githubusercontent.com/2022378/74561111-ff1a5c00-4f35-11ea-80d4-4c5afd30522f.png)

**Additional context**
See #158, #159 & #160

**Comment by robdefeo** [comment]
Closing due to archiving repository
