### ISSUE TITLE
Add buttons to modal for wizard step 2

### ISSUE THREAD

**Issue by tboeckmann** [mailchain/mailchain-web#159]
**Is your feature request related to a problem? Please describe.**
The modal needs to display buttons related to https://github.com/mailchain/mailchain-web/issues/157

**Describe the solution you'd like**
Buttons to include (no need to add methods):
- [ ]  `Back`: takes user back to Step 1
- [ ]  `Cancel`: close model and discards changes
- [ ]  `Save Changes`: Save changes and load the selected protocol and network

**Additional context**
![image](https://user-images.githubusercontent.com/2022378/74561111-ff1a5c00-4f35-11ea-80d4-4c5afd30522f.png)

**Comment by sa3664** [comment]
Hello ,

I would like to work on this issue.

Could you please assign this to me ?

Regards
Shivani

**Comment by tboeckmann** [comment]
Thanks @sa3664 

Let us know if you have any questions.

**Comment by robdefeo** [comment]
Closing due to archiving repository
