### ISSUE TITLE
Add dropdown to wizard step 2 (networks should be returned from Mailchain '/protocols' endpoint for each protocol)

### ISSUE THREAD

**Issue by tboeckmann** [mailchain/mailchain-web#160]
**Is your feature request related to a problem? Please describe.**
When a user wants to change protocol, they must select the network too

**Describe the solution you'd like**
When a protocol is selected in step 1 of the wizard, the dropdown options should be populated with the networks of that protocol (obtained from the `/protocols` endpoint).

The `protocols` object should already be available as the endpoint is loaded when the page loads.

**Additional context**
See https://github.com/mailchain/mailchain-web/projects/1 description for more information

**Comment by robdefeo** [comment]
Closing due to archiving repository
