### ISSUE TITLE
Add methods to modal for wizard step 2

### ISSUE THREAD

**Issue by tboeckmann** [mailchain/mailchain-web#161]
**Is your feature request related to a problem? Please describe.**
The buttons related to https://github.com/mailchain/mailchain-web/issues/157 need to work

**Describe the solution you'd like**
Buttons should be added in #159 

Buttons to add methods:
- [ ]  `Back`: takes user back to Step 1
- [ ]  `Cancel`: close model and discards changes
- [ ]  `Save Changes`: call method described in #164 

**Additional context**
![image](https://user-images.githubusercontent.com/2022378/74561111-ff1a5c00-4f35-11ea-80d4-4c5afd30522f.png)

**Comment by robdefeo** [comment]
Closing due to archiving repository
