### ISSUE TITLE
Add methods to modal for wizard step 1

### ISSUE THREAD

**Issue by tboeckmann** [mailchain/mailchain-web#162]
**Is your feature request related to a problem? Please describe.**
The buttons related to https://github.com/mailchain/mailchain-web/issues/157 need to work

**Describe the solution you'd like**
Buttons should be added in #158 

Buttons to add methods:
- [ ] `Ethereum`: Selects ethereum as the protocol and progresses to step 2
- [ ] `Polkadot`: Selects polkadot as the protocol and progresses to step 2

**Additional context**
![image](https://user-images.githubusercontent.com/2022378/74561095-f45fc700-4f35-11ea-97e1-101ec5b9a2b1.png)

**Comment by robdefeo** [comment]
Closing due to archiving repository
