### ISSUE TITLE
Display protocol buttons if they are returned from Mailchain '/protocols' endpoint

### ISSUE THREAD

**Issue by tboeckmann** [mailchain/mailchain-web#163]
**Is your feature request related to a problem? Please describe.**
The buttons related to https://github.com/mailchain/mailchain-web/issues/157 need to work

**Describe the solution you'd like**
Buttons should be added in #158 

Buttons to add methods:
- [ ] The buttons should display conditionally based on being included in the `/protocols` endpoint (using *ngIf).

**Additional context**
![image](https://user-images.githubusercontent.com/2022378/74561095-f45fc700-4f35-11ea-97e1-101ec5b9a2b1.png)

**Comment by robdefeo** [comment]
Closing due to archiving repository
