### ISSUE TITLE
Add/ update method for change of protocol and network on 'Save Changes'

### ISSUE THREAD

**Issue by tboeckmann** [mailchain/mailchain-web#164]
**Is your feature request related to a problem? Please describe.**
To save the protocol and network, and reload the settings related to https://github.com/mailchain/mailchain-web/issues/157, the existing method for changing network needs to be updated.

**Describe the solution you'd like**
- [ ] Update the relevant method to save changes and load the selected protocol and network
The button that calls this will be implemented in #159 

**Additional context**
![image](https://user-images.githubusercontent.com/2022378/74561111-ff1a5c00-4f35-11ea-80d4-4c5afd30522f.png)

**Comment by robdefeo** [comment]
Closing due to archiving repository
