### ISSUE TITLE
Bug: Inbox does not render message style

### ISSUE THREAD

**Issue by tboeckmann** [mailchain/mailchain-web#177]
**Describe the bug**
When I receive an HTML message, it is not formatted according to the styles in the message (see screen shot)

**To Reproduce**
1. Send an HTML message with nice formatting
2. Read message... it will not have nice formatting

**Expected behavior**
It should respect the styles of the incoming message

**Screenshots**
![image](https://user-images.githubusercontent.com/2022378/77848805-52333000-71bf-11ea-9d49-ca494a3add50.png)

 - Version [0.0.9]

**Comment by robdefeo** [comment]
Closing due to archiving repository
