### ISSUE TITLE
Bug: When recipient address starts with space, validation passes but message sending fails

### ISSUE THREAD

**Issue by tboeckmann** [mailchain/mailchain-web#193]
**Describe the bug**
When recipient address starts with space, validation passes but message sending fails.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Compose message'
2. Create a message, fill the recipient as " 0x..."
3. Send the message
4. See error in Mailchain client

**Expected behaviour**
Validation should fail before the message is sent, or the space should be stripped out.

Mailchain Inbox Version [0.0.14]

**Comment by robdefeo** [comment]
Closing due to archiving repository
