### ISSUE TITLE
'Unknown' error occurs when no keystore is present

### ISSUE THREAD

**Issue by tboeckmann** [mailchain/mailchain-web#212]
**Describe the bug**
When opening the inbox and no keystore file exists, the following message pops up:
![image](https://user-images.githubusercontent.com/2022378/93716976-aa456080-fb6a-11ea-9c06-84c839e54c5d.png)

The following call: `http://127.0.0.1:8080/api/addresses?protocol=ethereum&network=mainnet`
returns 

```{"code":500,"message":"open /Users/tboeckmann/.mailchain/.keystore: no such file or directory"}```

In the Terminal: `ERRO[2020-09-20T17:52:17+01:00] status 500: open /Users/xxxxxxx/.mailchain/.keystore: no such file or directory`

**To Reproduce**
1. Run mailchain serve with no keystore file
1. Go to 'https://inbox.mailchain.xyz/#/'
1. See error

**Expected behavior**
It should be more explicit and tell the user the keystore is missing

Version 15

**Comment by robdefeo** [comment]
Closing due to archiving repository
