### ISSUE TITLE
No error is displayed when Mailchain API is unable to connect to indexer

### ISSUE THREAD

**Issue by tboeckmann** [mailchain/mailchain-web#213]
**Describe the bug**
When running Mailchain and looking to access messages using the Inbox, but without the indexer running, an error 500 is returned, but no intuitive error displays in the interface.

```
{"code":500,"message":"Get http://localhost:8081/to?address=kWCKFhkg5m5XmGz2pbcUYhJK7RAf6jLj1wLM5J5junonVTH\u0026network=edgeware-mainnet\u0026protocol=substrate: dial tcp [::1]:8081: connect: connection refused"}
```

**To Reproduce**
1. Run `mailchain serve` (without the message indexer running)
2. Go to https://inbox.mailchain.xyz/#/
3. Change protocol to substrate and network to mainnnet
4. See error in console but not in inbox.

**Expected behavior**
An error message should pop up with helpful instructions to troubleshoot.

Version 0.0.15

**Comment by robdefeo** [comment]
Closing due to archiving repository
