### ISSUE TITLE
Trim whitespace from form values

### ISSUE THREAD

**Issue by tboeckmann** [mailchain/mailchain-web#214]
**Is your feature request related to a problem? Please describe.**
Address values  in form require a lookup (addresses/names for name resolution; addresses for public key lookup). Whitespace can sometime be added when a user copies and pastes a value.

**Describe the solution you'd like**
Trim these values in the mail editor

**Comment by hamrask** [comment]
Hi @tboeckmann,
I would like to contribute. may I write a helper function to achieve it?

**Comment by tboeckmann** [comment]
Hi @hamrask - thanks, it would be great to have your contribution.

I've assigned you the issue. Let us know on slack if you need any help.

**Comment by hamrask** [comment]
how can you contact you in slack? I'm new to slack.

**Comment by tboeckmann** [comment]
@hamrask take a look here: https://github.com/mailchain/community/blob/master/communication/README.md
