### ISSUE TITLE
Settings list returns applicationApiConfig values instead of looking up available networks

### ISSUE THREAD

**Issue by tboeckmann** [mailchain/mailchain-web#217]
**Describe the bug**
app/services/helpers/local-storage-server/local-storage-server.service.ts: getCurrentNetwork() obtains list of networks from applicationApiConfig.networks.
This should be deprecated to call the api endpoint for a list of current networks.

The stub file should also be updated.

**Comment by robdefeo** [comment]
Closing due to archiving repository
