### ISSUE TITLE
Extend support for Algorand in Mailchain Web settings

### ISSUE THREAD

**Issue by tboeckmann** [mailchain/mailchain-web#235]
**Is your feature request related to a problem? Please describe.**
In order to support Algorand, the Mailchain Web settings should show the protocol and supported networks (Mainnet, Testnet, Betanet)

**Describe the solution you'd like**
Something similar to this:
![image](https://user-images.githubusercontent.com/2022378/107858059-fe0e5a00-6e29-11eb-8e09-ec8dfb360718.png)

It should populate from the API.
Need to add test cases.

**Describe alternatives you've considered**
N/A

**Comment by tboeckmann** [comment]
Code added: https://github.com/mailchain/mailchain-web/tree/issues/235_settings

**Comment by robdefeo** [comment]
Closing due to archiving repository
