### ISSUE TITLE
Extend support for Algorand addresses (base32)

### ISSUE THREAD

**Issue by tboeckmann** [mailchain/mailchain-web#236]
**Is your feature request related to a problem? Please describe.**

From the [docs](https://developer.algorand.org/docs/features/accounts/), Algorand addresses:
* use Ed25519 elliptic-curve signatures
* are encoded as base32
* are not case-sensitive but are generally shown as upper case
* are 58 characters long

An example address is: `G2GTKMEEEEZH5TFUDYZMWWGXZLO3Z7765CR52ZXBBNCCMNPDYM3ZII7CSI`

**Describe the solution you'd like**
The mailchain inbox needs to:

- [x] display the address correctly in the UI
- [x] support address encoding: `"encoding": "base32/plain"`
- [ ] handle the address correctly when filtering for recipient messages (ignore case)
- [ ] send messages using upper-case sender and recipient addresses

**Describe alternatives you've considered**
The addresses should be correctly formatted by the mailchain client, but it's possible a user will not adhere to the formatting described above.

**Comment by robdefeo** [comment]
Closing due to archiving repository
