### ISSUE TITLE
Show balance and gas estimate in compose message

### ISSUE THREAD

**Issue by tboeckmann** [mailchain/mailchain-web#239]
**Is your feature request related to a problem? Please describe.**
I'm frustrated when I go to send a message in Mailchain and I don't know how much it will cost in fees and gas, or if I have enough on my account balance to send the message.

This is amplified with Ethereum's high gas price these days!

**Describe the solution you'd like**
Something like this, showing the Balance and Message cost (fee) for the sender address:
![image](https://user-images.githubusercontent.com/2022378/107877966-76772880-6ec7-11eb-8205-1217afbc8000.png)

It should update the balance when the sender address is changed.

**Describe alternatives you've considered**
The balance could be placed next to the address list on the left of the screen, but it's not relevant to most activities except sending a message.

**Additional context**

**Comment by tboeckmann** [comment]
Each protocol will have a different way of charging (e.g. Ethereum, Edgeware, Algorand).
If we do not have a method to calculate it, if should remain hidden.

**Comment by sa3664** [comment]
Hello , 

I would like to work on this issue . 

Could you please assign this to me . 

Regards
Shivani

**Comment by robdefeo** [comment]
Closing due to archiving repository
