### ISSUE TITLE
Set default from address to the current address in the inbox

### ISSUE THREAD

**Issue by tboeckmann** [mailchain/mailchain-web#51]
**Describe the bug**
The FROM address is always the first address from the Inbox list.
When I have multiple accounts and I'm working with an address other than the first one in the list, it's pretty likely that when I click compose, I want to send it from the current address.

**To Reproduce**
1. Select an address other than the first one on the list on the left.
2. Click on 'Compose'
3. See from address will be the first in the list (not the currently selected inbox)

**Expected behavior**
The from address should be the currently selected inbox.

**Additional context**

**Comment by nikosk686** [comment]
Hello,
this bug seems to have been resolved in the current version.
See `setCurrentAccountInFromAddressDropdown` in `inbox-compose.component.ts`.
The issue should be closed.

**Comment by tboeckmann** [comment]
Nice catch- thanks @nikosk686
