### ISSUE TITLE
Add explorer helper link to recipient address

### ISSUE THREAD

**Issue by tboeckmann** [mailchain/mailchain-web#62]
**Is your feature request related to a problem? Please describe.**
As a user, when I enter a recipient address, I want to double check the the address on a 3rd party site (e.g. Etherscan, Subscan etc)

**Describe the solution you'd like**
Add a helper link next to the field that takes me there.

*Ethereum*
`https://{{network}}.etherscan.io/address/{{address}}`

*Substrate*
`https://{{network}}.subscan.io/account/{{address}}`

*Algorand*
`https://algoexplorer.io/address/{{address}}`

Complexity may exist for custom networks/ testnets.

**Describe alternatives you've considered**
Offer a modal with previous transactions.... but why reinvent the wheel?

**Comment by robdefeo** [comment]
Closing due to archiving repository
