### ISSUE TITLE
Design Improvement: Color Scheme/ Bootstrap Theme

### ISSUE THREAD

**Issue by tboeckmann** [mailchain/mailchain-web#81]
Mailchain has had minimal design input and the interface looks bare. The base styling uses Bootstrap 4.0 running on Angular.

In line with the new logo design (#80) the [website](https://mailchain.xyz/) and the inbox application would benefit from a strong design in line with the [Mailchain tenets](https://github.com/mailchain/mailchain-specification/blob/master/mailchain_tenets.md), being clean, simple and modern.

Aside from mainstream frameworks (Angular, Bootstrap etc.), we've actively avoided using plugins and frameworks to reduce bloat and minimise surface area for bugs.

Requirements:
- Define a color palette/ bootstrap theme to give a better look and feel.

**Comment by tboeckmann** [comment]
Output of #80

**Comment by robdefeo** [comment]
Closing due to archiving repository
