### ISSUE TITLE
Send button is disabled after sending error

### ISSUE THREAD

**Issue by tboeckmann** [mailchain/mailchain-web#93]
**Is your feature request related to a problem? Please describe.**

When a message is sending, the &#x27;Send&#x27; button is disabled. Then, if the message sending fails, an error message is displayed, but the button remains disabled.

**To Reproduce**

1. Serve Mailchain with the wrong password
1. Go to Inbox 
1. Compose message
1. Click send
1. Close error message
1. Send Button is still disabled

**Describe the solution you&#x27;d like**

The button become re-enabled after the error has been dismissed.

`this.sendMessagesDisabled` should be set to false when modalConnectivityError when bsModalRef.hide is called.

This may mean separating out the error component (ModalConnectivityErrorComponent) into it new one for compose (FEELS LIKE IT)

**Screenshots**
![image](https://user-images.githubusercontent.com/2022378/68508847-65248280-0267-11ea-99a9-04ba84be4e6f.png)

**Desktop (please complete the following information):**
 - Version 0.0.3

**Comment by robdefeo** [comment]
Closing due to archiving repository
