### ISSUE TITLE
Error Modal Buttons: change text

### ISSUE THREAD

**Issue by tboeckmann** [mailchain/mailchain-web#94]
**Is your feature request related to a problem? Please describe.**

The Error Modal (modal-connectivity-error.component) is used in multiple scenarios. The button choices are currently:
Reload: reloads the page
Close: closes the modal

**Describe the solution you'd like**

Allow different buttons to be specified with different actions and button style.
E.g.
Button Text:
Reload
Close
Cancel
OK
Ignore
Skip

Actions:
reloads the page
closes modal
closes modal and does something

**Comment by robdefeo** [comment]
Closing due to archiving repository
