### ISSUE TITLE
In Firefox, Inbox fails to load correctly - CORS warning

### ISSUE THREAD

**Issue by tboeckmann** [mailchain/mailchain-web#98]
**Describe the bug**
When using Firefox 69, I load inbox.mailchain.xyz, but the Inbox fails to load correctly (see screenshot).

The Developer Console gives the following warning:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://127.0.0.1:8080/api/messages?protocol=ethereum&network=ropsten&address=0x123...789. (Reason: CORS request did not succeed).
```

Interestingly, calls to `http://127.0.0.1:8080/api/addresses` work, so this may be related to url parameters.

According to [Learn More](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSDidNotSucceed), this appears to be related to: https://bugzilla.mozilla.org/show_bug.cgi?id=1488740

**To Reproduce**
1. In Firefox, go to https://inbox.mailchain.xyz/#/
1. 'Loading' will not succeed.

**Expected behavior**
The Loading is either replaced by messages or a message indicating there are no messages ('Nothing here yet')

**Screenshots**
The 'Loading' screenshot: 
![image](https://user-images.githubusercontent.com/2022378/68549990-78b22380-03f6-11ea-8239-bcde0909a272.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser [Firefox]
 - Version [69]

**Additional context**

**Comment by tboeckmann** [comment]
Could be fixed by resolution of https://github.com/mailchain/mailchain/issues/121

**Comment by robdefeo** [comment]
Closing due to archiving repository
