### ISSUE TITLE
Ensure getAddresses handles protocols for network selection

### ISSUE THREAD

**Issue by tboeckmann** [mailchain/mailchain-web#99]
**Describe the bug**
`AddressesService.getAddresses` does not handle `protocol` to offer the correct networks for the currently selected protocol.

This issue exists in `Staging` branch.

![image](https://user-images.githubusercontent.com/2022378/68842414-3f133e00-06be-11ea-97ee-e622ec92e695.png)

In the staging-inbox
**To Reproduce**
1. Go to 'https://inbox-staging.mailchain.xyz/#/'
2. Click on 'change' networks
3. Click the drop-down
4. See flattened list of networks from all protocols

**Expected behavior**
The user should be able to select the protocol, then choose the network to work on.

**Screenshots**
![image](https://user-images.githubusercontent.com/2022378/68885194-99d38680-070c-11ea-8146-786c7d8c88f7.png)

**Additional context**
None

**Comment by tboeckmann** [comment]
This is what the modal should look like...

Select Protocol

![2019-12-01_17-03-34](https://user-images.githubusercontent.com/2022378/69917353-b4bc2f80-145c-11ea-88b4-12e8e3ff9abf.png)

Select Network

![2019-12-01_17-03-53](https://user-images.githubusercontent.com/2022378/69917346-a40bb980-145c-11ea-80b6-bbf9a2177d96.png)

**Comment by robdefeo** [comment]
Closing due to archiving repository
